### ISSUE TITLE
postinstall: `timer --updateDB`

### ISSUE THREAD

**Issue by kevinhowbrook** [danibram/time-tracker-cli#19]
Ubuntu npm install results in 
```
sh: 1: timer: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! time-tracker-cli@2.3.0 postinstall: `timer --updateDB`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the time-tracker-cli@2.3.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by danibram** [comment]
First of all, thank you for improve timer.
Did you have timer installed before? Or its your first time?

Thanks in advice!

**Comment by kevinhowbrook** [comment]
I think this is my first time on my new computer. I had it on another system before though

**Comment by danibram** [comment]
Ok, im sorry for the inconvenience, it was a code to keep consistent the database if you had an older version of the timer, and you update to a new version.  So you can keep using timer as normal. I will fix it when I have time. Thank you!

**Comment by kevinhowbrook** [comment]
ok, if you let me know what code/file I can take a look

**Comment by danibram** [comment]
I removed that thing to prevent this error
